### PR TITLE
Promise v3

### LINKED ISSUE #143: react/promise 3.0 support?
Hi, are there any plans to support react/promise 3.0?

### PR DESCRIPTION
**Pull request by WyriHaximus**
Resolves: #143

### CODE REVIEW

**Comment by lookyman** [comment]
I see that the failing checks on PHP 7.1 are caused by PHPStan requiring PHP 7.2. It's coming up on four years since PHP 7.1 EOL, maybe it's time to drop it?

**Comment by WyriHaximus** [comment]
> I see that the failing checks on PHP 7.1 are caused by PHPStan requiring PHP 7.2. It's coming up on four years since [PHP 7.1 EOL](https://www.php.net/eol.php), maybe it's time to drop it?

In short yes, the bigger question is more do we want v3 in the 0.5 range or take it into 0.6, drop up to 8.1, and a whole bunch of changes? Having the same question in https://github.com/WyriHaximus/reactphp-throw-unhandled-rejected-promises mainly putting it at 7.1 for this package, but if we would raise it I would put 1.0.0 out with 7.1 and 1.1.0 right after with lets say 8.1

**Comment by akadlec** [comment]
it will be great to finish this. bunny is only package in my project which is holding me back with old promise package :/

**Comment by WyriHaximus** [comment]
> it will be great to finish this. bunny is only package in my project which is holding me back with old promise package :/ 

While I agree, it is complicated. V3 handles unhandled rejections differently and I want to make sure that is taken care of well before merging and releasing this.

**Comment by jakubvojacek** [comment]
Any idea as to when this could be finished, please?

**Comment by WyriHaximus** [comment]
Closed via #147, wasn't about to get this to work in 0.5, so went v3 only for 0.6 instead. Essentially #147 is the result of starting to do some internal updates 😅 .

**Pull request closed without merging**
