### PR TITLE
Typehint to DateTimeInterface to allow DateTimeImmutable values

### PR DESCRIPTION
**Pull request by fritz-gerneth**
This is for the PHP->AMQP type conversion only. Most of our code uses DateTimeImmutable types ( as our dates are not mutable :)). This safes us from having to cast them. 
From what I understood this part is not auto-generated. This should also be no BC break.

### CODE REVIEW

**Comment by WyriHaximus** [comment]
> From what I understood this part is not auto-generated. This should also be no BC break.

Had to double check this, but indeed it doesn't look auto-generated :+1: . Do you think adding a unit test to enforcing this would make sense? Just in the case when we do generate code again we don't accidentally drop it

**Comment by fritz-gerneth** [comment]
I see some tests expect a specific RabbitMQ configuration - is there some Docker image / definitions file for the expected setup?

**Comment by WyriHaximus** [comment]
> I see some tests expect a specific RabbitMQ configuration - is there some Docker image / definitions file for the expected setup?

I'll get onto that, there isn't one but there are some things we could improve and having a single command to run all tests locally should be one of them.

**Comment by WyriHaximus** [comment]
@fritz-gerneth Someone beat me to it: https://github.com/jakubkulhan/bunny/pull/97

**Comment by fritz-gerneth** [comment]
> 
> 
> @fritz-gerneth Someone beat me to it: #97

Sorry to hear that ;) Will add the test once #97 is merged then.

**Comment by WyriHaximus** [comment]
> > @fritz-gerneth Someone beat me to it: #97
> 
> Sorry to hear that ;) Will add the test once #97 is merged then.

Hey I'll take it once all is green :D

**Comment by mermshaus** [comment]
Sorry, I didn’t notice this until now. I had most parts of #97 lying around for quite a while before I finally managed to split things into commits and to prepare the PR. :slightly_smiling_face: My main intention is to fix issues with disconnection of the synchronous client (see eg. #93). (There are some more places in the tutorial where it is done wrong.) This gave me a lot of gray hair in a larger test suite that ran into random heartbeat timeouts after 10 minutes or so.

**Comment by WyriHaximus** [comment]
@fritz-gerneth #97 is in, great thanks to @mermshaus for that 👍

**Comment by WyriHaximus** [comment]
@mermshaus Yeah I understand that, it's a great package, but it can use some fixes and improvements for certain cases. ANd I appreciate your work on improving it 👍 !

**Comment by fritz-gerneth** [comment]
Tests are added now. Test setup works pretty flawless 👍

**Pull request merged**
