### PR TITLE
Bump php dep to ~8.0

### PR DESCRIPTION
**Pull request by standa**
This would really help us. Thanks! :)

### CODE REVIEW

**Comment by janlanger** [comment]
Bunny contains required parameters after optional, which is deprecated since PHP 8 and emits E_DEPRECATED. It's in ClientMethods for example.

Also, testing on PHP 8 should be set up on Travis.

**Comment by WyriHaximus** [comment]
@standa cool thanks for this PR :+1: ! Not sure yet why the Travis build isn't started.

**Comment by edudobay** [comment]
Hi! I've addressed these issues in another PR: https://github.com/jakubkulhan/bunny/pull/102. Feel free to incorporate any changes from there. Please note that there is a PHP 7.0 compatibility issue.

**Comment by standa** [comment]
Hi @edudobay, thank you for picking this up. I think my PR became redundant by you creating yours. So I am closing mine as a lesser one.

**Pull request closed without merging**
