### PR TITLE
Seconds float -> int

### PR DESCRIPTION
**Pull request by simPod**

### CODE REVIEW

**Comment by jakubkulhan** [comment]
Hi. `$maxSeconds` is intentionally `float` as it works with split-second time.

**Comment by simPod** [comment]
In that case my assuption is invalid. Thanks

**Comment by simPod** [comment]
Or should I rebase that autoload fix only?

**Comment by jakubkulhan** [comment]
Yes, you can send PR for the autoload fix. (Also please remove `classmap` from autoload sections, it's better to autoloader optimization when running `composer install` https://getcomposer.org/doc/articles/autoloader-optimization.md)

**Pull request closed without merging**
