### PR TITLE
Fix: added PHP8.1

### PR DESCRIPTION
**Pull request by bckp**

### CODE REVIEW

**Comment by bckp** [comment]
You have added tests etc, but do not edited composer.json, so PHP8.1 is still not supported from Composer perspective....
see https://getcomposer.org/doc/articles/versions.md#caret-version-range-

**Comment by WyriHaximus** [comment]
@bckp It installs just fine on PHP 8.1 for me: 
image

And looking at that caret explanation it also matches PHP 8.1. Or are you experiencing something different?

**Comment by bckp** [comment]
Hmm, now installs fine... Sorry, it must be some dependency issue, as for me it always install 0.2.4... thanks @WyriHaximus

**Comment by WyriHaximus** [comment]
Don't hesitate to reach out if you run into any issues in the future

**Pull request closed without merging**
