### PR TITLE
add channel property to message

### PR DESCRIPTION
**Pull request by Tatikoma**
When working with multiple channels it's a bit ugly to keep in mind which channel received message. This patch allows to use more simple code.

### CODE REVIEW

**Comment by jakubkulhan** [comment]
Could you provide example use case when you need to work with multiple channels in PHP application? In `consume` message handler you get reference to the channel the message has been received on:

```php
$client = new Client();
$channel = $client->channel();

$channel->consume(function (Message $message, Channel $channel) {
    // do something with $message and $channel, e.g. $channel->ack($message);
}, ...);
```

Wouldn't this suffice?

**Comment by Tatikoma** [comment]
If simplistically, i have two queue: one with messages, second with users. I need script that combine messages to users.

For messages queue i need channel with large prefetch count, for users queue i need channel with small prefetch count. So i need two channels, and message ack'ing 'll not be inside consumer callback.

I can provide complete code, if u wanna.

**Comment by jakubkulhan** [comment]
I don't think that passing channel through message objects is a good idea for this use case. Why not create class that will hold references to both channels and handle message streams merging and acking?

**Comment by Tatikoma** [comment]
In my opinion it's looks okay that message knows which channel delivered them to worker. The processing of the message without knowledge of the channel is impossible.

Also PhpAmqpLib provides access to channel via message. https://github.com/videlalvaro/php-amqplib
```
<?php
/** @var AMQPMessage $message */
$message->delivery_info['channel']->basic_ack($message);
```

Here is sample code (i dont check promise result, to save a bit time for writting this, real code is very ugly).

```
<?php
$loop = \React\EventLoop\Factory::create();
$client = new \Bunny\Async\Client($loop);
$users = [];
$messages = [];
$client->connect()->then(function($client)){
    $client->channel()->then(function($channel) use(&$messages){
        $channel->consume(function($message, $channel) use(&$messages){
            $messages[] = $message;
        }, 'queue-name-1');
    });
    $client->channel()->then(function($channel) use(&$users){
        $channel->consume(function($message, $channel) use(&$users){
            $users[] = $message;
        });
    });
});
$loop->addPeriodicalTimer(0.1, function() use(&$messages, &$users){
    if(count($users) < 1 || count($messages) < 15){
        return;
    }
    echo "User is: " . $user->content . "\n";
    $user = array_shift($users);
    $user->channel->ack($user);
    for($i  = 0; $i < 15; $i ++){
        $message = array_shift($messages);
        echo "Message is: " . $message->content;
        $message->channel->ack($message);
    }
});
```
Can u please show me the way to write it more simple?

**Comment by jakubkulhan** [comment]
Just save the reference to the channel after creating it.

```php
use Bunny\Async\Client;
use Bunny\Channel;
use Bunny\Message;
use React\EventLoop\Factory;
use React\EventLoop\LoopInterface;

/** @var LoopInterface $loop */
$loop = Factory::create();
$client = new Client($loop);
/** @var Message[] $users */
$users = [];
/** @var Message[] $messages */
$messages = [];
/** @var Channel $userChannel */
$userChannel = null;
/** @var Channel $messageChannel */
$messageChannel = null;

$client->connect()->then(function (Client $client) use (&$users, &$messages, &$userChannel, &$messageChannel) {
    $client->channel()->then(function (Channel $channel) use (&$messageChannel, &$messages) {
        $messageChannel = $channel;

        $messageChannel->qos(0, 10000);
        $messageChannel->consume(function (Message $message) use (&$messages) {
            $messages[] = $message;
        }, 'queue-name-1');
    });

    $client->channel()->then(function (Channel $channel) use (&$userChannel, &$users) {
        $userChannel = $channel;

        $userChannel->qos(0, 50);
        $userChannel->consume(function (Message $message) use (&$users) {
            $users[] = $message;
        }, 'queue-name-2');
    });
});

$loop->addPeriodicTimer(0.1, function () use (&$users, &$messages, &$userChannel, &$messageChannel) {
    if (count($users) < 1 || count($messages) < 15) {
        return;
    }

    /** @var Message $user */
    $user = array_shift($users);
    echo "User is: " . $user->content . "\n";
    $userChannel->ack($user);
    
    for ($i = 0; $i < 15; $i++) {
        /** @var Message $message */
        $message = array_shift($messages);
        echo "Message is: " . $message->content . "\n";
        
        $messageChannel->ack($message);
    }
});

$loop->run();
```

This is much cleaner way. As `Message` class' [doc comment says](https://github.com/jakubkulhan/bunny/blob/master/src/Bunny/Message.php#L5), it is a *convenience crate for transferring messages through app,* nothing more. 

Acking messages through channel property of a message also violates [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter), this is not good OO design. Unfortunately PhpAmqpLib is full of OO design flaws. It is one of the reasons for which this AMQP library has been created.

**Pull request closed without merging**
