### PR TITLE
feat: add support for SSL

### LINKED ISSUE #77: Connect using SSL protocol
Hello. Is it possible to connect to RabbitMQ using SSL connection? I'm getting error message "RabbitMQ: Broken pipe or closed connection.".

### PR DESCRIPTION
**Pull request by rtm-ctrlz**
Added usage of `stream_context_set_option` for setting SSL options.
Added tests with certificate generation and ssl-enabled configuration for RabbitMQ.
Added some configuration examples for common use cases see `examples/ssl` directory.
Mentioned SSL support in main `README.md`.

Some notes:
- RabbitMQ added [sysctl format](https://www.rabbitmq.com/configure.html#config-file) since 3.7.0, so there are both configuration file versions `prior 3.7.0` and `sysctl`.
- Tests covers only connections, any other tests should works same way as via plain tcp.
- There is no way to detect any errors in SSL options, so in case of error we will get exception with `Could not connect to...` message.

Resolves #77

### CODE REVIEW

**Comment by rtm-ctrlz** [comment]
Personally, I have no objection change the parameter name, but this code will not look so neat:
```
stream_context_set_option($context, ['ssl' => $this->options['tls']])
```
If you are OK with that - make this change.

**Comment by rtm-ctrlz** [comment]
See #89 ;)

**Comment by rtm-ctrlz** [comment]
Synced branch jakubkulhan/bunny:master

**Comment by WyriHaximus** [comment]
> See #89 ;)

Will have a look at it tomorrow :+1: .

**Comment by WyriHaximus** [comment]
> Personally, I have no objection regarding parameter name change, but this code will not look so neat:
> 
> ```
> stream_context_set_option($context, ['ssl' => $this->options['tls']])
> ```
> 
> If you are OK with that - I'll make this change.
> 
> Also, should `examples/ssl`, `test/ssl`, variables in Makefile and filenames for RabbitMQ configs (for tests and examples) directory be renamed?

Yeah this suddenly makes sense looking at #89 🤐 !

**Pull request merged**
