### PR TITLE
Fix drop connection by RabbitMQ

### PR DESCRIPTION
**Pull request by viras777**
Fix if RabbitMQ closed the connection due to incorrect login/password.
Similar problems in here issues:
[Change state to error when ClientException is throw #115](https://github.com/jakubkulhan/bunny/issues/115)
or
[Failing connections cause exceptions thrown outside of Promise #74](https://github.com/jakubkulhan/bunny/issues/74)
or
[ClientException #59](https://github.com/jakubkulhan/bunny/issues/59)

### CODE REVIEW

**Comment by WyriHaximus** [comment]
Thank you for filing this PR, could you rebase on the latest changes in master now that #106, and do you think it is possible to test this?

**Comment by viras777** [comment]
I tested on my test server and now works on the production server

**Comment by WyriHaximus** [comment]
@viras777 Thanks for the update. Any clue what it fails for certain jobs?

**Comment by viras777** [comment]
In the function awaitConnectionTune I added interception of all exceptions to be able to process in reject.
like this:
Connection = (new Client())->connect()->then()->otherwise();

Because of this, the tests do not pass, they expect another type of exception

**Comment by viras777** [comment]
Sometimes there are missed hearbeats with an error on the rabbitmq server: "missing heartbeats from client, timeout: 60s" and bunny take 100 CPU for a while.
This happens when $nextStreamSelectTimeout < $ now < $ stopTime
For example call method run(1) and wait 60s

**Review by WyriHaximus — APPROVED** [review]
Thanks, sorry for the late merge. Planning to release this in a few days

**Comment by WyriHaximus** [comment]
Odd, CI blow up, but not on lowest possible dependencies. Will fix before releasing

**Pull request merged**
